"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import importlib.metadata

__title__: str = "my-company-sdk"
__version__: str = "0.0.1"
__openapi_doc_version__: str = "0.1.0"
__gen_version__: str = "2.493.32"
__user_agent__: str = "speakeasy-sdk/python 0.0.1 2.493.32 0.1.0 my-company-sdk"

try:
    if __package__ is not None:
        __version__ = importlib.metadata.version(__package__)
except importlib.metadata.PackageNotFoundError:
    pass
