"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from my_company_sdk.types import BaseModel
from my_company_sdk.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class ReadItemItemsItemIDGetRequestTypedDict(TypedDict):
    random_id: bool


class ReadItemItemsItemIDGetRequest(BaseModel):
    random_id: Annotated[
        bool, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
